name: workflow

on:
    push:
        branches:
            - main
        paths-ignore:
            - 'README.md'
permissions:
    id-token: write
    contents: read

jobs:
    integration:
        name: Continuous Integration
        strategy:
            matrix:
                python-version: [3.12.8]
        runs-on: ubuntu-latest
        steps:
            - name: Set up Python ${{ matrix.python-version }}  
              uses: actions/setup-python@v5  
              with:  
                python-version: ${{ matrix.python-version }}
            - name: Checkout Code
              uses: actions/checkout@v4
            # - name: Wheels prerequisites
            #   run: pip install setuptools wheel
            - name: Cache
              uses: actions/cache@v3
              with:
                path: ./venv
                key: ${{ runner.os }}-venv-${{ hashFiles('**/requirements*.txt') }}
            - name: Install dependencies
              if: steps.cache-venv.outputs.cache-hit != 'true'
              run: |
                python -m venv venv
                source venv/bin/activate
                pip install -r requirements.txt
            - name: Test
              run: |
                source venv/bin/activate
                pip install pytest 
                pytest -v
    build-imag-and-push-dockerhub:
      name: Continous Delivery
      needs:
        integration
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repository
          uses: actions/checkout@v3
        - name: Log in to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_TOKEN }}
    
        - name: Build Docker image
          run: |
            docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/your-repo-name:latest .
    
        - name: Push Docker image to Docker Hub
          run: |
            docker push ${{ secrets.DOCKER_HUB_USERNAME }}/your-repo-name:latest     
        





